server:
  port: 4500
myCustomVar:
  devName: Antonio
  authCode: xyz458
---
environment: production
myCustomVar:
  devName: Tonio
  authCode: xyz457
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 7070
---
environment: testing
myCustomVar:
  devName: notInTest
  authCode: NoNeedAuthCodeHere
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
server:
  port: 4000
